// Code generated by go run ./cmd/astclonegen; DO NOT EDIT.

package astclone

import (
	"go/ast"
	"reflect"
)

func shallowCopy(n ast.Node) ast.Node {
	switch orig := n.(type) {
	case *ast.ArrayType:
		cloned := *orig
		return &cloned
	case *ast.AssignStmt:
		cloned := *orig
		cloned.Lhs = append([]ast.Expr(nil), orig.Lhs...)
		cloned.Rhs = append([]ast.Expr(nil), orig.Rhs...)
		return &cloned
	case *ast.BadDecl:
		cloned := *orig
		return &cloned
	case *ast.BadExpr:
		cloned := *orig
		return &cloned
	case *ast.BadStmt:
		cloned := *orig
		return &cloned
	case *ast.BasicLit:
		cloned := *orig
		return &cloned
	case *ast.BinaryExpr:
		cloned := *orig
		return &cloned
	case *ast.BlockStmt:
		cloned := *orig
		cloned.List = append([]ast.Stmt(nil), orig.List...)
		return &cloned
	case *ast.BranchStmt:
		cloned := *orig
		return &cloned
	case *ast.CallExpr:
		cloned := *orig
		cloned.Args = append([]ast.Expr(nil), orig.Args...)
		return &cloned
	case *ast.CaseClause:
		cloned := *orig
		cloned.Body = append([]ast.Stmt(nil), orig.Body...)
		cloned.List = append([]ast.Expr(nil), orig.List...)
		return &cloned
	case *ast.ChanType:
		cloned := *orig
		return &cloned
	case *ast.CommClause:
		cloned := *orig
		cloned.Body = append([]ast.Stmt(nil), orig.Body...)
		return &cloned
	case *ast.Comment:
		cloned := *orig
		return &cloned
	case *ast.CommentGroup:
		cloned := *orig
		cloned.List = append([]*ast.Comment(nil), orig.List...)
		return &cloned
	case *ast.CompositeLit:
		cloned := *orig
		cloned.Elts = append([]ast.Expr(nil), orig.Elts...)
		return &cloned
	case *ast.DeclStmt:
		cloned := *orig
		return &cloned
	case *ast.DeferStmt:
		cloned := *orig
		return &cloned
	case *ast.Directive:
		cloned := *orig
		return &cloned
	case *ast.Ellipsis:
		cloned := *orig
		return &cloned
	case *ast.EmptyStmt:
		cloned := *orig
		return &cloned
	case *ast.ExprStmt:
		cloned := *orig
		return &cloned
	case *ast.Field:
		cloned := *orig
		cloned.Names = append([]*ast.Ident(nil), orig.Names...)
		return &cloned
	case *ast.FieldList:
		cloned := *orig
		cloned.List = append([]*ast.Field(nil), orig.List...)
		return &cloned
	case *ast.File:
		cloned := *orig
		cloned.Comments = append([]*ast.CommentGroup(nil), orig.Comments...)
		cloned.Decls = append([]ast.Decl(nil), orig.Decls...)
		cloned.Imports = append([]*ast.ImportSpec(nil), orig.Imports...)
		cloned.Unresolved = append([]*ast.Ident(nil), orig.Unresolved...)
		return &cloned
	case *ast.ForStmt:
		cloned := *orig
		return &cloned
	case *ast.FuncDecl:
		cloned := *orig
		return &cloned
	case *ast.FuncLit:
		cloned := *orig
		return &cloned
	case *ast.FuncType:
		cloned := *orig
		return &cloned
	case *ast.GenDecl:
		cloned := *orig
		cloned.Specs = append([]ast.Spec(nil), orig.Specs...)
		return &cloned
	case *ast.GoStmt:
		cloned := *orig
		return &cloned
	case *ast.Ident:
		cloned := *orig
		return &cloned
	case *ast.IfStmt:
		cloned := *orig
		return &cloned
	case *ast.ImportSpec:
		cloned := *orig
		return &cloned
	case *ast.IncDecStmt:
		cloned := *orig
		return &cloned
	case *ast.IndexExpr:
		cloned := *orig
		return &cloned
	case *ast.IndexListExpr:
		cloned := *orig
		cloned.Indices = append([]ast.Expr(nil), orig.Indices...)
		return &cloned
	case *ast.InterfaceType:
		cloned := *orig
		return &cloned
	case *ast.KeyValueExpr:
		cloned := *orig
		return &cloned
	case *ast.LabeledStmt:
		cloned := *orig
		return &cloned
	case *ast.MapType:
		cloned := *orig
		return &cloned
	case *ast.Package:
		cloned := *orig
		cloned.Files = cloneMap(orig.Files)
		cloned.Imports = cloneMap(orig.Imports)
		return &cloned
	case *ast.ParenExpr:
		cloned := *orig
		return &cloned
	case *ast.RangeStmt:
		cloned := *orig
		return &cloned
	case *ast.ReturnStmt:
		cloned := *orig
		cloned.Results = append([]ast.Expr(nil), orig.Results...)
		return &cloned
	case *ast.SelectStmt:
		cloned := *orig
		return &cloned
	case *ast.SelectorExpr:
		cloned := *orig
		return &cloned
	case *ast.SendStmt:
		cloned := *orig
		return &cloned
	case *ast.SliceExpr:
		cloned := *orig
		return &cloned
	case *ast.StarExpr:
		cloned := *orig
		return &cloned
	case *ast.StructType:
		cloned := *orig
		return &cloned
	case *ast.SwitchStmt:
		cloned := *orig
		return &cloned
	case *ast.TypeAssertExpr:
		cloned := *orig
		return &cloned
	case *ast.TypeSpec:
		cloned := *orig
		return &cloned
	case *ast.TypeSwitchStmt:
		cloned := *orig
		return &cloned
	case *ast.UnaryExpr:
		cloned := *orig
		return &cloned
	case *ast.ValueSpec:
		cloned := *orig
		cloned.Names = append([]*ast.Ident(nil), orig.Names...)
		cloned.Values = append([]ast.Expr(nil), orig.Values...)
		return &cloned
	default:
		return nil
	}
}

func replaceChild(parent ast.Node, oldChild ast.Node, newChild ast.Node) bool {
	switch p := parent.(type) {
	case *ast.ArrayType:
		if replaceField(&p.Elt, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Len, oldChild, newChild) {
			return true
		}
		return false
	case *ast.AssignStmt:
		if replaced, ok := replaceSlice(p.Lhs, oldChild, newChild); ok {
			p.Lhs = replaced
			return true
		}
		if replaced, ok := replaceSlice(p.Rhs, oldChild, newChild); ok {
			p.Rhs = replaced
			return true
		}
		return false
	case *ast.BadDecl:
		return false
	case *ast.BadExpr:
		return false
	case *ast.BadStmt:
		return false
	case *ast.BasicLit:
		return false
	case *ast.BinaryExpr:
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Y, oldChild, newChild) {
			return true
		}
		return false
	case *ast.BlockStmt:
		if replaced, ok := replaceSlice(p.List, oldChild, newChild); ok {
			p.List = replaced
			return true
		}
		return false
	case *ast.BranchStmt:
		if replaceField(&p.Label, oldChild, newChild) {
			return true
		}
		return false
	case *ast.CallExpr:
		if replaced, ok := replaceSlice(p.Args, oldChild, newChild); ok {
			p.Args = replaced
			return true
		}
		if replaceField(&p.Fun, oldChild, newChild) {
			return true
		}
		return false
	case *ast.CaseClause:
		if replaced, ok := replaceSlice(p.Body, oldChild, newChild); ok {
			p.Body = replaced
			return true
		}
		if replaced, ok := replaceSlice(p.List, oldChild, newChild); ok {
			p.List = replaced
			return true
		}
		return false
	case *ast.ChanType:
		if replaceField(&p.Value, oldChild, newChild) {
			return true
		}
		return false
	case *ast.CommClause:
		if replaced, ok := replaceSlice(p.Body, oldChild, newChild); ok {
			p.Body = replaced
			return true
		}
		if replaceField(&p.Comm, oldChild, newChild) {
			return true
		}
		return false
	case *ast.Comment:
		return false
	case *ast.CommentGroup:
		if replaced, ok := replaceSlice(p.List, oldChild, newChild); ok {
			p.List = replaced
			return true
		}
		return false
	case *ast.CompositeLit:
		if replaced, ok := replaceSlice(p.Elts, oldChild, newChild); ok {
			p.Elts = replaced
			return true
		}
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		return false
	case *ast.DeclStmt:
		if replaceField(&p.Decl, oldChild, newChild) {
			return true
		}
		return false
	case *ast.DeferStmt:
		if replaceField(&p.Call, oldChild, newChild) {
			return true
		}
		return false
	case *ast.Directive:
		return false
	case *ast.Ellipsis:
		if replaceField(&p.Elt, oldChild, newChild) {
			return true
		}
		return false
	case *ast.EmptyStmt:
		return false
	case *ast.ExprStmt:
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.Field:
		if replaceField(&p.Comment, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaced, ok := replaceSlice(p.Names, oldChild, newChild); ok {
			p.Names = replaced
			return true
		}
		if replaceField(&p.Tag, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		return false
	case *ast.FieldList:
		if replaced, ok := replaceSlice(p.List, oldChild, newChild); ok {
			p.List = replaced
			return true
		}
		return false
	case *ast.File:
		if replaced, ok := replaceSlice(p.Comments, oldChild, newChild); ok {
			p.Comments = replaced
			return true
		}
		if replaced, ok := replaceSlice(p.Decls, oldChild, newChild); ok {
			p.Decls = replaced
			return true
		}
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaced, ok := replaceSlice(p.Imports, oldChild, newChild); ok {
			p.Imports = replaced
			return true
		}
		if replaceField(&p.Name, oldChild, newChild) {
			return true
		}
		if replaced, ok := replaceSlice(p.Unresolved, oldChild, newChild); ok {
			p.Unresolved = replaced
			return true
		}
		return false
	case *ast.ForStmt:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Cond, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Init, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Post, oldChild, newChild) {
			return true
		}
		return false
	case *ast.FuncDecl:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Name, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Recv, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		return false
	case *ast.FuncLit:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		return false
	case *ast.FuncType:
		if replaceField(&p.Params, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Results, oldChild, newChild) {
			return true
		}
		if replaceField(&p.TypeParams, oldChild, newChild) {
			return true
		}
		return false
	case *ast.GenDecl:
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaced, ok := replaceSlice(p.Specs, oldChild, newChild); ok {
			p.Specs = replaced
			return true
		}
		return false
	case *ast.GoStmt:
		if replaceField(&p.Call, oldChild, newChild) {
			return true
		}
		return false
	case *ast.Ident:
		return false
	case *ast.IfStmt:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Cond, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Else, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Init, oldChild, newChild) {
			return true
		}
		return false
	case *ast.ImportSpec:
		if replaceField(&p.Comment, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Name, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Path, oldChild, newChild) {
			return true
		}
		return false
	case *ast.IncDecStmt:
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.IndexExpr:
		if replaceField(&p.Index, oldChild, newChild) {
			return true
		}
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.IndexListExpr:
		if replaced, ok := replaceSlice(p.Indices, oldChild, newChild); ok {
			p.Indices = replaced
			return true
		}
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.InterfaceType:
		if replaceField(&p.Methods, oldChild, newChild) {
			return true
		}
		return false
	case *ast.KeyValueExpr:
		if replaceField(&p.Key, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Value, oldChild, newChild) {
			return true
		}
		return false
	case *ast.LabeledStmt:
		if replaceField(&p.Label, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Stmt, oldChild, newChild) {
			return true
		}
		return false
	case *ast.MapType:
		if replaceField(&p.Key, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Value, oldChild, newChild) {
			return true
		}
		return false
	case *ast.Package:
		if replaced, ok := replaceMapValue(p.Files, oldChild, newChild); ok {
			p.Files = replaced
			return true
		}
		return false
	case *ast.ParenExpr:
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.RangeStmt:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Key, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Value, oldChild, newChild) {
			return true
		}
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.ReturnStmt:
		if replaced, ok := replaceSlice(p.Results, oldChild, newChild); ok {
			p.Results = replaced
			return true
		}
		return false
	case *ast.SelectStmt:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		return false
	case *ast.SelectorExpr:
		if replaceField(&p.Sel, oldChild, newChild) {
			return true
		}
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.SendStmt:
		if replaceField(&p.Chan, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Value, oldChild, newChild) {
			return true
		}
		return false
	case *ast.SliceExpr:
		if replaceField(&p.High, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Low, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Max, oldChild, newChild) {
			return true
		}
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.StarExpr:
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.StructType:
		if replaceField(&p.Fields, oldChild, newChild) {
			return true
		}
		return false
	case *ast.SwitchStmt:
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Init, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Tag, oldChild, newChild) {
			return true
		}
		return false
	case *ast.TypeAssertExpr:
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.TypeSpec:
		if replaceField(&p.Comment, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Name, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		if replaceField(&p.TypeParams, oldChild, newChild) {
			return true
		}
		return false
	case *ast.TypeSwitchStmt:
		if replaceField(&p.Assign, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Body, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Init, oldChild, newChild) {
			return true
		}
		return false
	case *ast.UnaryExpr:
		if replaceField(&p.X, oldChild, newChild) {
			return true
		}
		return false
	case *ast.ValueSpec:
		if replaceField(&p.Comment, oldChild, newChild) {
			return true
		}
		if replaceField(&p.Doc, oldChild, newChild) {
			return true
		}
		if replaced, ok := replaceSlice(p.Names, oldChild, newChild); ok {
			p.Names = replaced
			return true
		}
		if replaceField(&p.Type, oldChild, newChild) {
			return true
		}
		if replaced, ok := replaceSlice(p.Values, oldChild, newChild); ok {
			p.Values = replaced
			return true
		}
		return false
	default:
		return false
	}
}

func replaceField[T ast.Node](field *T, oldChild ast.Node, newChild ast.Node) bool {
	if field == nil {
		return false
	}
	current := ast.Node(*field)
	if !sameNode(current, oldChild) {
		return false
	}
	replaced, ok := newChild.(T)
	if !ok {
		return false
	}
	*field = replaced
	return true
}

func replaceSlice[T ast.Node](items []T, oldChild ast.Node, newChild ast.Node) ([]T, bool) {
	for i := range items {
		current := ast.Node(items[i])
		if !sameNode(current, oldChild) {
			continue
		}
		replaced, ok := newChild.(T)
		if !ok {
			return nil, false
		}
		out := append([]T(nil), items...)
		out[i] = replaced
		return out, true
	}
	return nil, false
}

func replaceMapValue[K comparable, V ast.Node](items map[K]V, oldChild ast.Node, newChild ast.Node) (map[K]V, bool) {
	for key, value := range items {
		current := ast.Node(value)
		if !sameNode(current, oldChild) {
			continue
		}
		replaced, ok := newChild.(V)
		if !ok {
			return nil, false
		}
		out := cloneMap(items)
		out[key] = replaced
		return out, true
	}
	return nil, false
}

func cloneMap[K comparable, V any](items map[K]V) map[K]V {
	if items == nil {
		return nil
	}
	out := make(map[K]V, len(items))
	for key, value := range items {
		out[key] = value
	}
	return out
}

func sameNode(a ast.Node, b ast.Node) bool {
	if a == nil || b == nil {
		return a == b
	}
	va := reflect.ValueOf(a)
	vb := reflect.ValueOf(b)
	if va.Kind() != reflect.Pointer || vb.Kind() != reflect.Pointer {
		return false
	}
	return va.Type() == vb.Type() && va.Pointer() == vb.Pointer()
}
