package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/importer"
	"go/types"
	"os"
	"sort"
	"strings"
)

const (
	kindNone fieldKind = iota
	kindNode
	kindSlice
	kindSliceNode
	kindMap
	kindMapNode
)

type fieldKind int

type fieldMeta struct {
	Name        string
	Type        string
	Kind        fieldKind
	Replaceable bool
}

type typeMeta struct {
	Name   string
	Fields []fieldMeta
}

func main() {
	outPath := flag.String("out", "copy_replace.go", "output path")
	flag.Parse()

	meta, err := collectMetadata()
	if err != nil {
		fail("collect metadata", err)
	}

	src := buildSource(meta)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fail("gofmt generated source", err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fail("write output", err)
	}
}

func collectMetadata() ([]typeMeta, error) {
	pkg, err := importer.Default().Import("go/ast")
	if err != nil {
		return nil, err
	}

	nodeObj := pkg.Scope().Lookup("Node")
	if nodeObj == nil {
		return nil, fmt.Errorf("go/ast.Node not found")
	}
	nodeIface, ok := nodeObj.Type().Underlying().(*types.Interface)
	if !ok {
		return nil, fmt.Errorf("go/ast.Node is not interface")
	}

	names := pkg.Scope().Names()
	sort.Strings(names)

	meta := make([]typeMeta, 0, len(names))
	for _, name := range names {
		obj := pkg.Scope().Lookup(name)
		tn, ok := obj.(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := tn.Type().(*types.Named)
		if !ok {
			continue
		}
		st, ok := named.Underlying().(*types.Struct)
		if !ok {
			continue
		}
		if !types.AssignableTo(types.NewPointer(named), nodeIface) {
			continue
		}

		fields := make([]fieldMeta, 0, st.NumFields())
		for field := range st.Fields() {
			kind := classifyField(field.Type(), nodeIface)
			fields = append(fields, fieldMeta{
				Name:        field.Name(),
				Type:        types.TypeString(field.Type(), typeQualifier),
				Kind:        kind,
				Replaceable: kind == kindNode || kind == kindSliceNode || kind == kindMapNode,
			})
		}
		sort.Slice(fields, func(i, j int) bool {
			return fields[i].Name < fields[j].Name
		})

		meta = append(meta, typeMeta{Name: name, Fields: fields})
	}
	return meta, nil
}

func typeQualifier(pkg *types.Package) string {
	if pkg == nil {
		return ""
	}
	return pkg.Name()
}

func classifyField(t types.Type, nodeIface *types.Interface) fieldKind {
	if types.AssignableTo(t, nodeIface) {
		return kindNode
	}
	if sl, ok := t.Underlying().(*types.Slice); ok {
		if types.AssignableTo(sl.Elem(), nodeIface) {
			return kindSliceNode
		}
		return kindSlice
	}
	if mp, ok := t.Underlying().(*types.Map); ok {
		if types.AssignableTo(mp.Elem(), nodeIface) {
			return kindMapNode
		}
		return kindMap
	}
	return kindNone
}

func buildSource(meta []typeMeta) string {
	var b strings.Builder
	b.WriteString("// Code generated by go run ./cmd/astcowgen; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("package astcow\n")
	b.WriteString("\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"go/ast\"\n")
	b.WriteString("\t\"reflect\"\n")
	b.WriteString(")\n")
	b.WriteString("\n")

	writeShallowCopy(&b, meta)
	b.WriteString("\n")
	writeReplaceChild(&b, meta)
	b.WriteString("\n")
	writeHelpers(&b)

	return b.String()
}

func writeShallowCopy(b *strings.Builder, meta []typeMeta) {
	b.WriteString("func shallowCopy(n ast.Node) ast.Node {\n")
	b.WriteString("\tswitch orig := n.(type) {\n")
	for _, t := range meta {
		b.WriteString("\tcase *ast.")
		b.WriteString(t.Name)
		b.WriteString(":\n")
		b.WriteString("\t\tcloned := *orig\n")
		for _, f := range t.Fields {
			switch f.Kind {
			case kindSlice:
				b.WriteString("\t\tcloned.")
				b.WriteString(f.Name)
				b.WriteString(" = append(")
				b.WriteString(f.Type)
				b.WriteString("(nil), orig.")
				b.WriteString(f.Name)
				b.WriteString("...)\n")
			case kindSliceNode:
				b.WriteString("\t\tcloned.")
				b.WriteString(f.Name)
				b.WriteString(" = append(")
				b.WriteString(f.Type)
				b.WriteString("(nil), orig.")
				b.WriteString(f.Name)
				b.WriteString("...)\n")
			case kindMap:
				b.WriteString("\t\tcloned.")
				b.WriteString(f.Name)
				b.WriteString(" = cloneMap(orig.")
				b.WriteString(f.Name)
				b.WriteString(")\n")
			case kindMapNode:
				b.WriteString("\t\tcloned.")
				b.WriteString(f.Name)
				b.WriteString(" = cloneMap(orig.")
				b.WriteString(f.Name)
				b.WriteString(")\n")
			}
		}
		b.WriteString("\t\treturn &cloned\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

func writeReplaceChild(b *strings.Builder, meta []typeMeta) {
	b.WriteString("func replaceChild(parent ast.Node, oldChild ast.Node, newChild ast.Node) bool {\n")
	b.WriteString("\tswitch p := parent.(type) {\n")
	for _, t := range meta {
		b.WriteString("\tcase *ast.")
		b.WriteString(t.Name)
		b.WriteString(":\n")
		hasReplace := false
		for _, f := range t.Fields {
			switch f.Kind {
			case kindNode:
				hasReplace = true
				b.WriteString("\t\tif replaceField(&p.")
				b.WriteString(f.Name)
				b.WriteString(", oldChild, newChild) {\n")
				b.WriteString("\t\t\treturn true\n")
				b.WriteString("\t\t}\n")
			case kindSliceNode:
				hasReplace = true
				b.WriteString("\t\tif replaced, ok := replaceSlice(p.")
				b.WriteString(f.Name)
				b.WriteString(", oldChild, newChild); ok {\n")
				b.WriteString("\t\t\tp.")
				b.WriteString(f.Name)
				b.WriteString(" = replaced\n")
				b.WriteString("\t\t\treturn true\n")
				b.WriteString("\t\t}\n")
			case kindMapNode:
				hasReplace = true
				b.WriteString("\t\tif replaced, ok := replaceMapValue(p.")
				b.WriteString(f.Name)
				b.WriteString(", oldChild, newChild); ok {\n")
				b.WriteString("\t\t\tp.")
				b.WriteString(f.Name)
				b.WriteString(" = replaced\n")
				b.WriteString("\t\t\treturn true\n")
				b.WriteString("\t\t}\n")
			}
		}
		if !hasReplace {
			b.WriteString("\t\treturn false\n")
			continue
		}
		b.WriteString("\t\treturn false\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

func writeHelpers(b *strings.Builder) {
	b.WriteString("func replaceField[T ast.Node](field *T, oldChild ast.Node, newChild ast.Node) bool {\n")
	b.WriteString("\tif field == nil {\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcurrent := ast.Node(*field)\n")
	b.WriteString("\tif !sameNode(current, oldChild) {\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	b.WriteString("\treplaced, ok := newChild.(T)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	b.WriteString("\t*field = replaced\n")
	b.WriteString("\treturn true\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("func replaceSlice[T ast.Node](items []T, oldChild ast.Node, newChild ast.Node) ([]T, bool) {\n")
	b.WriteString("\tfor i := range items {\n")
	b.WriteString("\t\tcurrent := ast.Node(items[i])\n")
	b.WriteString("\t\tif !sameNode(current, oldChild) {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treplaced, ok := newChild.(T)\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\treturn nil, false\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tout := append([]T(nil), items...)\n")
	b.WriteString("\t\tout[i] = replaced\n")
	b.WriteString("\t\treturn out, true\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil, false\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("func replaceMapValue[K comparable, V ast.Node](items map[K]V, oldChild ast.Node, newChild ast.Node) (map[K]V, bool) {\n")
	b.WriteString("\tfor key, value := range items {\n")
	b.WriteString("\t\tcurrent := ast.Node(value)\n")
	b.WriteString("\t\tif !sameNode(current, oldChild) {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treplaced, ok := newChild.(V)\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\treturn nil, false\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tout := cloneMap(items)\n")
	b.WriteString("\t\tout[key] = replaced\n")
	b.WriteString("\t\treturn out, true\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil, false\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("func cloneMap[K comparable, V any](items map[K]V) map[K]V {\n")
	b.WriteString("\tif items == nil {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tout := make(map[K]V, len(items))\n")
	b.WriteString("\tfor key, value := range items {\n")
	b.WriteString("\t\tout[key] = value\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn out\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("func sameNode(a ast.Node, b ast.Node) bool {\n")
	b.WriteString("\tif a == nil || b == nil {\n")
	b.WriteString("\t\treturn a == b\n")
	b.WriteString("\t}\n")
	b.WriteString("\tva := reflect.ValueOf(a)\n")
	b.WriteString("\tvb := reflect.ValueOf(b)\n")
	b.WriteString("\tif va.Kind() != reflect.Pointer || vb.Kind() != reflect.Pointer {\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn va.Type() == vb.Type() && va.Pointer() == vb.Pointer()\n")
	b.WriteString("}\n")
}

func fail(action string, err error) {
	var buf bytes.Buffer
	buf.WriteString("astcowgen: ")
	buf.WriteString(action)
	buf.WriteString(": ")
	buf.WriteString(err.Error())
	fmt.Fprintln(os.Stderr, buf.String())
	os.Exit(1)
}
